version: '3.8'
services:
  gateway:
    build:
      dockerfile:
        gateway/Dockerfile
    image:
      shareit-gateway
    container_name:
      shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      server:
        condition: service_started
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build:
      dockerfile:
        server/Dockerfile
    image:
      shareit-server
    container_name:
      shareit-server
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres

  db:
    image:
      postgres
    container_name:
      postgres
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
